const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('ekp', {
  appVersion: () => ipcRenderer.invoke('app:version'),
  catalog: () => ipcRenderer.invoke('catalog'), state: () => ipcRenderer.invoke('state:get'), saveState: state => ipcRenderer.invoke('state:set', state),
  userDataGroups: () => ipcRenderer.invoke('user-data:groups'), exportUserData: groupIds => ipcRenderer.invoke('user-data:export', groupIds), prepareUserDataImport: () => ipcRenderer.invoke('user-data:prepare-import'), importUserData: groupIds => ipcRenderer.invoke('user-data:import', groupIds),
  catalogMetadata: () => ipcRenderer.invoke('catalog:metadata'), updateHistory: () => ipcRenderer.invoke('updates:history'),
  databaseUpdateStatus: () => ipcRenderer.invoke('database:update-status'), checkDatabaseUpdate: () => ipcRenderer.invoke('database:check-update'), installDatabaseUpdate: manifest => ipcRenderer.invoke('database:install-update', manifest), onDatabaseUpdateProgress: callback => { const listener = (_event, value) => callback(value); ipcRenderer.on('database:update-progress', listener); return () => ipcRenderer.removeListener('database:update-progress', listener); },
  checkProgramUpdate: () => ipcRenderer.invoke('program-update:check'), installProgramUpdate: () => ipcRenderer.invoke('program-update:install'), onProgramUpdateProgress: callback => { const listener = (_event, value) => callback(value); ipcRenderer.on('program-update:progress', listener); return () => ipcRenderer.removeListener('program-update:progress', listener); },
  notes: () => ipcRenderer.invoke('notes:list'), saveNote: note => ipcRenderer.invoke('notes:save', note), deleteNote: id => ipcRenderer.invoke('notes:delete', id),
  importedNotes: () => ipcRenderer.invoke('imported-notes:list'), deleteImportedNote: id => ipcRenderer.invoke('imported-notes:delete', id), exportNotes: payload => ipcRenderer.invoke('notes:export', payload), importNotes: () => ipcRenderer.invoke('notes:import'), promoteImportedNote: note => ipcRenderer.invoke('imported-notes:promote', note),
  addAttachments: id => ipcRenderer.invoke('attachments:add', id), deleteAttachment: file => ipcRenderer.invoke('attachments:delete', file), readAttachment: file => ipcRenderer.invoke('attachments:read', file), openFile: file => ipcRenderer.invoke('file:open', file), openDbn: file => ipcRenderer.invoke('dbn:open', file), readPdf: file => ipcRenderer.invoke('dbn:read-pdf', file),
  pdfBookmarks: documentId => ipcRenderer.invoke('pdf-bookmarks:list', documentId), addPdfBookmark: payload => ipcRenderer.invoke('pdf-bookmarks:add', payload), deletePdfBookmark: payload => ipcRenderer.invoke('pdf-bookmarks:delete', payload),
  openExternal: url => ipcRenderer.invoke('external:open', url),
  edessbConfig: () => ipcRenderer.invoke('edessb:config'), edessbProjects: () => ipcRenderer.invoke('edessb-projects:list'), createEdessbProject: payload => ipcRenderer.invoke('edessb-projects:create', payload), deleteEdessbProject: projectId => ipcRenderer.invoke('edessb-projects:delete', projectId), selectEdessbPdf: () => ipcRenderer.invoke('edessb-projects:select-pdf'), addEdessbRevision: payload => ipcRenderer.invoke('edessb-projects:add-revision', payload), updateEdessbRevision: payload => ipcRenderer.invoke('edessb-projects:update-revision', payload), openEdessbRevision: payload => ipcRenderer.invoke('edessb-projects:open-revision', payload), deleteEdessbRevision: payload => ipcRenderer.invoke('edessb-projects:delete-revision', payload), openEdessbDocumentsFolder: identifier => ipcRenderer.invoke('edessb-projects:open-documents-folder', identifier),
  materialsLibrary: () => ipcRenderer.invoke('materials:list'), saveMaterial: payload => ipcRenderer.invoke('materials:save', payload), deleteMaterial: id => ipcRenderer.invoke('materials:delete', id), openMaterialsDatabase: () => ipcRenderer.invoke('materials:open-database'), selectMaterialFiles: () => ipcRenderer.invoke('materials:select-files'), openMaterialAttachment: storedName => ipcRenderer.invoke('materials:open-attachment', storedName), openMaterialAttachmentsFolder: () => ipcRenderer.invoke('materials:open-attachments-folder'),
  archicadStatus: port => ipcRenderer.invoke('archicad:status', port), archicadConnections: () => ipcRenderer.invoke('archicad:connections'), activeArchicadConnection: () => ipcRenderer.invoke('archicad:foreground-connection'), archicadProjects: () => ipcRenderer.invoke('archicad-projects:list'), createArchicadProject: title => ipcRenderer.invoke('archicad-projects:create', title), setArchicadProjectConnection: payload => ipcRenderer.invoke('archicad-projects:set-connection', payload), exportArchicadElements: projectId => ipcRenderer.invoke('archicad-projects:export-elements', projectId), openArchicadProjectFile: payload => ipcRenderer.invoke('archicad-projects:open', payload), saveArchicadProjectFile: payload => ipcRenderer.invoke('archicad-projects:save-copy', payload), importArchicadProject: payload => ipcRenderer.invoke('archicad-projects:import', payload), deleteArchicadProject: projectId => ipcRenderer.invoke('archicad-projects:delete', projectId), deleteArchicadProjectFile: payload => ipcRenderer.invoke('archicad-projects:delete-file', payload),
  window: { minimize: () => ipcRenderer.invoke('window:minimize'), maximize: () => ipcRenderer.invoke('window:maximize'), releaseAlwaysOnTop: () => ipcRenderer.invoke('window:release-always-on-top'), close: () => ipcRenderer.invoke('window:close') }
});
